### ISSUE TITLE
xIEEsc resource does not correctly disable IE Enhanced Security

### ISSUE THREAD

**Issue by TravisEz13** [dsccommunity/xSystemSecurity#1]
## Repro
1. On Windows 8.1 or Windows Server 2012R2
2. Logon as a user 
3. Use xIEEsc resource to disable IE Enhanced Security on a server.
4. Use IE to browse to any website, as the user you logged in as in step 2.
## Expected

No prompts
## Actual

Prompts

**Comment by pcgeek86** [comment]
@TravisEz13  Which operating system are you using? Is it a fresh build?

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by TravisEz13** [comment]
Updated the initial issue with the info,  I looked at fixing the issue, but it requires calling an API.  There was an issue with the API with either needing to run as a user or interactively.  I haven't tried the fix with WMF5's RunAs feature.

**Comment by johlju** [comment]
This resource is being moved to ComputerManagementDsc. Currently the proposed resource in ComputerManagementDsc restarts the node after this value is set. Another (worse?) option is to stop the Explorer process. I don't know what API the previous comment is referring to, but that might be an option in the future. I mention this issue in the code.
