### ISSUE TITLE
xFileSystemAccessRule: not working with files?

### ISSUE THREAD

**Issue by oleksii-iaroshchuk** [dsccommunity/xSystemSecurity#12]
I have the following simple rule to give "Modify" permission on the file:

```
xFileSystemAccessRule WorkerRoleNLogInternalLog
{
    Path            = $workerRoleNLogInternalLogFile
    Identity        = $appUserName
    Rights          = "Modify"
    Ensure          = "Present"
}
```

Applying this configuration gives me the following error:

```
Exception calling "SetAccessRule" with "1" argument(s): "No flags can be set.
Parameter name: inheritanceFlags"
```

**Does `xFileSystemAccessRule` work with files?** If not, I guess this must be fixed.
For now I workarounded this using `Script` resource with the following instructions:

```
$acl = Get-ACL $using:workerRoleNLogInternalLogFile
$accessRule = New-Object System.Security.AccessControl.FileSystemAccessRule($using:appUserName, 
    "Modify", "Allow")
$acl.SetAccessRule($accessRule)
Set-ACL $using:workerRoleNLogInternalLogFile $acl

```

**Comment by kwirkykat** [comment]
Closing this as a duplicate of #11

**Comment by jonathanan** [comment]
@kwirkykat This still appears to be an issue with 1.3.0.0

**Comment by matthewcsisson** [comment]
This was not a duplicate. of #11

The solutions is removing the inheritance and propagation from your access rule for files.
For Folders:
$AccessRule = New-Object System.Security.AccessControl.FileSystemAccessRule($Identity, $rights, $inheritance, $propagation, $accessControl)

For Files:
$AccessRule = New-Object System.Security.AccessControl.FileSystemAccessRule($Identity, $rights, $accessControl)
