### ISSUE TITLE
IEEsc Bug on Server 2016

### ISSUE THREAD

**Issue by gesbeckj** [dsccommunity/xSystemSecurity#15]
The IEEsc setting does not work correctly on Server 2016. It correctly places the registry entry on the system that works for Server 2012/2012R2. However, it appears that Server 2016 uses a different registry entry for identifying the status of IEEsc.

**Comment by SwarfegaGit** [comment]
I'm testing this fine with no problems found.  The registry values have not changed and do still exist in 2016.

I can confirm though that it does appear to not have worked if you are making the change whilst logged in interactively.  You need to sign out and back in to see the changes to place.

**Comment by gesbeckj** [comment]
You're right. Once I do a log off it works perfectly, it just isn't interactive.
