### ISSUE TITLE
xUAC Not working with latest PDSCresources

### ISSUE THREAD

**Issue by SylvainMartel** [dsccommunity/xSystemSecurity#17]
When using PSdscResources 2.8.0.0 and xUAC we get the error message that the "Force" parameter should be used.

To solve this we added Force = $true in xUAC.schema.psm1 to the various registry call.  Not sure it was the right things to do, but it works again now.

Exemple:
<pre>   $UacKey = "HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System"
    Registry ConsentPromptBehaviorAdmin
    {       
        Ensure = "Present"
        Key = $UacKey
        ValueName = "ConsentPromptBehaviorAdmin"
        ValueData = [string] $ConsentPromptBehaviorAdmin
        ValueType = "Dword"
        Force = $true
    }
</pre>

**Comment by johlju** [comment]
This module have been deprecated and the resource xUac have been replaced by refactored resource UserAccountControl in the module ComputerManagementDsc. Please report any issues in that repository when using the new resource.
