### ISSUE TITLE
xUAC should prompt for a reboot

### ISSUE THREAD

**Issue by tysonjhayes** [dsccommunity/xSystemSecurity#2]
Modifying the specific registry keys will require the system be rebooted to apply the UAC settings. The resource should tell the system to reboot to actually apply this setting.

I believe if the resource sets $global:DSCMachineStatus = 1 the machine will reboot itself, can anyone confirm this before I make a Pull Request?

**Comment by vors** [comment]
Yes, that's correct. Reboot would happen only if [LCM](https://technet.microsoft.com/en-us/library/dn249922.aspx) (Local Configuration Manager) property `RebootNodeIfNeeded` is set to `$true` in the meta-config.

**Comment by kwirkykat** [comment]
@tysonjhayes Has there been a pull request submitted for this?

**Comment by tysonjhayes** [comment]
@kwirkykat I have not, if someone else has time feel free, unfortunatey I've been quite busy with other things!

**Comment by johlju** [comment]
This module have been deprecated and the resource xUac have been replaced by refactored resource UserAccountControl in the module ComputerManagementDsc. Please report any issues in that repository when using the new resource.

This was enhanced in the refactored resource.
