### ISSUE TITLE
The syntax of the xUac resource doesn't show the possible values for the Setting property

### ISSUE THREAD

**Issue by MathieuBuisson** [dsccommunity/xSystemSecurity#5]
The syntax of the xUac resource doesn't show the possible values for the Setting property :

![xuac](https://cloud.githubusercontent.com/assets/10233108/14988245/f2e569de-114a-11e6-836b-e8d4d1c83919.PNG)

According the README.md, this property takes a fixed set of possible values, so we should see them in the syntax.

Also, because of this, the ISE cannot autocomplete the values for this Setting property.

**Comment by johlju** [comment]
This module have been deprecated and the resource xUac have been replaced by refactored resource UserAccountControl in the module ComputerManagementDsc. Please report any issues in that repository when using the new resource. 

We should add conceptual help to the ComputerManagementDsc repo, but it would still not make it possible to autocomplete the values. 🤔 I opened a issue for the conceptual help.
