### ISSUE TITLE
xUAC should allow to set the "ask for password" parameter

### ISSUE THREAD

**Issue by Zulgrib** [dsccommunity/xSystemSecurity#8]
UAC is technically able to ask for credentials instead of "yes/no", we should be able to change that setting too.

If it is already possible, the readme file needs to be improved to reflect that.

**Comment by johlju** [comment]
This module have been deprecated and the resource xUac have been replaced by refactored resource UserAccountControl in the module ComputerManagementDsc. Please report any issues in that repository when using the new resource if the issue was not resolved.
